### ISSUE TITLE
Lacrosse2mqtt auf einem HEITEC Lora ESP32 V2

### ISSUE THREAD

**Issue by SFKUG** [seife/lacrosse2mqtt#1]
Hallo Stefan, ich versuche derzeit Deinen Code für o.g. Contoller anzupassen bzw. zum laufen zu bringen.
Dies gelingt mir leider nicht, zunächst habe ich den Code als ZIP (Library) in die Ardunino IDE (Version 1.8.19 unter Win) geladen, das
entsprechende Board eingestellt und es wird die LittleFS.h angemeckert. Diese ist aber installiert/eingebunden, kann ich unter meinen Librarys finden, habe dann die Angabe auf "LITTLESF.h" angepasst. Dann kommt der nächste Fehler, "HTTPUpdateServer.h" kann nicht
gefunden werden, okay, habe ich auch als zusätzliche Datei in das Projektverzeichnis hinzugefügt. Dann kommt der nächste Fehler:
"lacrosse2mqtt-main/globals.h:22:22: error: redefinition of 'const uint8_t KEY_BUILTIN' static const uint8_t KEY_BUILTIN = 0;" und so geht das weiter und weiter. Was mache ich falsch ? Könntest Du mir behilflich sein ?

Vielen Dank und beste Grüße Sandro

**Comment by seife** [comment]
Hallo Sandro,
zufällig habe ich (schon länger, aber hatte es nur lokal hier liegen...) Support für das heltec_lora_32v2 Board eingebaut, ich hab das mal eben committed und gepushed.
Damit ist das KEY_BUILTIN weg.

Für LittleFS solltest du dein arduino-esp32 updaten, ab Version 2.0.0 ist das keine externe Library mehr sondern im core integriert, als LittleFS.h. Ich glaube zur Version 2 hat sich die URL für den boarverwalter geändert, irgendwas war da. Einfach in der arduino-esp32 doku nachschauen. Mit älteren arduino-esp32 cores wird es auch sonst nicht funktionieren befürchte ich, das habe ich einfach schon ewig nicht mehr getestet.
HTTPUpdateServer ist beim core neuer als 1.0.5 dabei, ich vermute also daß du eine ziemlich alte arduino-esp32 installation hast.

Ich baue immer in der Konsole mit "./compile.sh -e", das exportiert das binary so daß ich es übers webfrontend flashen kann, aber ich habe heute extra die arduino GUI installiert und damit getestet, es ließ sich auch für beide Boards bauen (das HELTEC natürlich nur mit der Änderung die ich gerade gepushed habe).

**Comment by SFKUG** [comment]
Hallo Stefan, das war die Lösung Umstieg auf > Arduino IDE 2.x - Danke - funktioniert wunderbar !
Viele Grüße und einen fleißigen Osterhase ... Sandro

**Comment by seife** [comment]
Schön daß es jetzt funktioniert.
Als Hinweis, falls das jemand später mal findet: die IDE ist nicht der entscheidende Punkt, sondern der darin enthaltene arduino-esp32 core. Ich hatte es mit der alten 1.8.6 IDE getestet, aber halt mit aktuellem core :-)
