### ISSUE TITLE
Transmit mode? 

### ISSUE THREAD

**Issue by lucadentella** [seife/lacrosse2mqtt#3]
Hi! Your project works great for getting data from "real" La Crosse sensors.

I'm trying to implement the opposite: I've a couple of Zigbee sensors already working with HomeAssistant via zigbeetomqtt and I'd like to send data to a quite old La Crosse station that supports TX29 sensors.

I implemented the code to reiceive data from mosquitto topics but I'm stuck when trying to implement the correct flow and register values to transmit data... maybe did you also work on that? In SX127x.* I cannot find anything related to transmit mode and I'm finding some issues when porting the "tx part" of other libraries (RadioLib).

Thanks!

**Comment by lucadentella** [comment]
Hi

I managed to write the code to send data, if you're interested:
https://github.com/lucadentella/LaCrosseSender

Thanks again, your project was very helpful!

**Comment by seife** [comment]
Sorry, I only noticed this issue now.
I was also already thinking about something like this to avoid having to re-pair my ITdirect weather station every time it crashes and needs the batteries replaced ;-) but did not yet get to it.
I will certainly have a look at your LaCrosseSender project.
Thanks!

**Comment by lucadentella** [comment]
Thanks for your comment, in the meantime I also designed  standalone sensor, in case someone wants a direct replacement without the need for HomeAssistant, MQTT and so on... [LaCrosseSensor](https://github.com/lucadentella/LaCrosseSensor)
